from __future__ import annotations

from typing import Final

from systograph.core.services.component_bridge_models import (
    ComponentBridgeCandidateSpec,
    ComponentBridgeRule,
)

COMPONENT_BRIDGE_RULES: Final[tuple[ComponentBridgeRule, ...]] = (
    ComponentBridgeRule(
        rule_ids=frozenset(
            {
                "docker_qdrant_image_detected",
                "code_pattern_vector_store_qdrant",
            }
        ),
        fact_kinds=frozenset({"docker_service", "vector_store_client"}),
        candidates=(
            ComponentBridgeCandidateSpec(
                slot="vector_store",
                kind="vector_db",
                name="Qdrant",
                provider="qdrant",
            ),
        ),
    ),
    ComponentBridgeRule(
        rule_ids=frozenset({"docker_pgvector_image_detected"}),
        fact_kinds=frozenset({"docker_service"}),
        candidates=(
            ComponentBridgeCandidateSpec(
                slot="vector_store",
                kind="vector_db",
                name="pgvector",
                provider="pgvector",
            ),
        ),
    ),
    ComponentBridgeRule(
        rule_ids=frozenset({"docker_chromadb_chroma_image_detected"}),
        fact_kinds=frozenset({"docker_service"}),
        candidates=(
            ComponentBridgeCandidateSpec(
                slot="vector_store",
                kind="http_vector_store",
                name="Chroma",
                provider="chroma",
            ),
        ),
    ),
    ComponentBridgeRule(
        rule_ids=frozenset({"code_pattern_vector_store_chroma"}),
        fact_kinds=frozenset({"vector_store_client"}),
        candidates=(
            ComponentBridgeCandidateSpec(
                slot="vector_store",
                kind="vector_db",
                name="Chroma",
                provider="chroma",
            ),
        ),
    ),
    ComponentBridgeRule(
        rule_ids=frozenset(
            {
                "code_pattern_vector_store_chroma_http",
                "code_pattern_vector_store_chroma_async_http",
            }
        ),
        fact_kinds=frozenset({"vector_store_client"}),
        candidates=(
            ComponentBridgeCandidateSpec(
                slot="vector_store",
                kind="http_vector_store",
                name="Chroma HTTP",
                provider="chroma_http",
            ),
        ),
    ),
    ComponentBridgeRule(
        rule_ids=frozenset({"code_pattern_vector_store_chroma_persistent"}),
        fact_kinds=frozenset({"vector_store_client"}),
        candidates=(
            ComponentBridgeCandidateSpec(
                slot="vector_store",
                kind="local_persistent_vector_store",
                name="Chroma Persistent",
                provider="chroma_persistent",
            ),
        ),
    ),
    ComponentBridgeRule(
        rule_ids=frozenset({"docker_ollama_image_detected"}),
        fact_kinds=frozenset({"docker_service"}),
        candidates=(
            ComponentBridgeCandidateSpec(
                slot="llm",
                kind="local_llm_runtime",
                name="Ollama",
                provider="ollama",
            ),
        ),
    ),
    ComponentBridgeRule(
        rule_ids=frozenset({"code_pattern_llm_chat_openai"}),
        fact_kinds=frozenset({"llm_call"}),
        candidates=(
            ComponentBridgeCandidateSpec(
                slot="llm",
                kind="external_llm_provider",
                name="OpenAI",
                provider="openai",
            ),
        ),
    ),
    ComponentBridgeRule(
        rule_ids=frozenset(
            {
                "code_pattern_embedding_openai",
                "code_pattern_embedding_openai_sdk_create",
            }
        ),
        fact_kinds=frozenset({"embedding"}),
        candidates=(
            ComponentBridgeCandidateSpec(
                slot="embedding_model",
                kind="embedding_provider",
                name="OpenAI Embeddings",
                provider="openai",
            ),
        ),
    ),
    ComponentBridgeRule(
        rule_ids=frozenset(
            {
                "code_pattern_route_fastapi",
                "code_pattern_route_flask",
                "code_pattern_route_express",
            }
        ),
        fact_kinds=frozenset({"api_route", "route_endpoint"}),
        candidates=(
            ComponentBridgeCandidateSpec(
                slot="app_api_or_orchestrator",
                kind="api_route",
                name="Application API",
                provider=None,
            ),
        ),
    ),
    ComponentBridgeRule(
        rule_ids=frozenset({"code_pattern_retriever_as_retriever"}),
        fact_kinds=frozenset({"retriever"}),
        candidates=(
            ComponentBridgeCandidateSpec(
                slot="retriever",
                kind="retriever",
                name="Retriever",
                provider=None,
            ),
        ),
    ),
    ComponentBridgeRule(
        rule_ids=frozenset({"code_pattern_vector_store_qdrant"}),
        fact_kinds=frozenset({"vector_store_client"}),
        required_file_tokens=frozenset({"retriever"}),
        candidates=(
            ComponentBridgeCandidateSpec(
                slot="retriever",
                kind="retriever",
                name="Retriever",
                provider=None,
            ),
        ),
    ),
    ComponentBridgeRule(
        rule_ids=frozenset({"code_pattern_prompt_template"}),
        fact_kinds=frozenset({"prompt_template"}),
        candidates=(
            ComponentBridgeCandidateSpec(
                slot="prompt_builder",
                kind="prompt_template",
                name="Prompt Template",
                provider=None,
            ),
        ),
    ),
)
